[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
    "openai-messages-token-helper==0.1.10",
    "openai==1.57.0",
    "opencv-python>=4.11.0.86",
]
